export declare function setHubUrl(hubUrl: string): void;
export declare function setVideos(local: HTMLVideoElement, remote: HTMLVideoElement): void;
export declare function setRoomId(roomId:string): void;
export declare function setSettings(localUniqueUserId: string, remoteUniqueUserId: string): void;
export declare function startPeerConnection(iceServerUrl: string = 'stun:stun.l.google.com:19302'): Promise<void>;
export declare function startCall(sendOffer:boolean = true): Promise<void>;
export declare function startScreenShare(sendOffer:boolean = true): Promise<void>;
export declare function switchVideoToScreenShare(): Promise<void>;
export declare function switchScreenShareToVideo(): Promise<void>;
export declare function invite(): Promise<void>;
export declare function inviteAll(): Promise<void>;
export declare function acceptInvite(roomId: string): Promise<void>;
export declare function startLocalMedia(): Promise<void>;
export declare function startLocalScreenMedia(startAudio:boolean = false): Promise<void>;
export declare function setAudio(mute: boolean): void;
export declare function setVideo(stopVideo: boolean): void;
export declare function toggleAudio(): void;
export declare function toggleVideo(): void;
export declare function endCall(): Promise<void>;
export declare function startHubConnection(): Promise<void>;
export declare function sendMessage(message:string): void;
export declare function transferFile(data: Uint8Array, fileName: string, mimeType: string): void;
export declare function startRecording(): void;
export declare function stopRecording(): void;