export declare function setHubUrl(hubUrl: string): void;
export declare function setVideos(local: HTMLVideoElement, remote: HTMLVideoElement): void;
export declare function setRoomId(roomId): void;
export declare function setLocalUniqueId(localUniqueId: string): void;
export declare function startPeerConnection(iceServerUrl: string = 'stun:stun.l.google.com:19302'): Promise<void>;
export declare function startCall(sendOffer:boolean = true): Promise<void>;
export declare function startScreenShare(sendOffer:boolean = true): Promise<void>;
export declare function switchVideoToScreenShare(): Promise<void>;
export declare function switchScreenShareToVideo(): Promise<void>;
export declare function invite(remoteUniqueId: string): Promise<void>;
export declare function inviteGroup(remoteUniqueIds: string[]): Promise<void>;
export declare function inviteAll(): Promise<void>;
export declare function acceptInvite(roomId: string): Promise<void>;
export declare function startLocalMedia(startVideo: boolean = true, startAudio: boolean = true): Promise<void>;
export declare function startLocalScreenMedia(startAudio = false): Promise<void>;
export declare function setAudio(mute): void;
export declare function setVideo(stopVideo): void;
export declare function toggleAudio(): void;
export declare function toggleVideo(): void;
export declare function endCall(): Promise<void>;
export declare function startHubConnection(): Promise<void>;
export declare function sendMessage(message:string): void;
export declare function transferFile(data: Uint8Array, fileName: string, mimeType: string): void;
export declare function startRecording(): void;
export declare function stopRecording(): void;